import React,{useEffect,useMemo,useState} from "react";
import {useNavigate} from "react-router-dom";
import {Bot,Code2,Palette,Search,Brain,FolderOpen,Workflow,Users,Command,Orbit, Sparkles, Plus, Trash2, Copy, Check, Send, Wand2, LayoutGrid, Zap, Shield, Mic, Globe2} from "lucide-react";

const glass="rounded-2xl border border-white/10 bg-white/[.035] backdrop-blur-xl";
const modules=[
 {id:"chat",name:"Chat",icon:Bot,path:"/"},{id:"codex",name:"xCodex",icon:Code2,path:"/codex"},{id:"studio",name:"AI Studio",icon:Palette,path:"/studio"},{id:"research",name:"Research",icon:Globe2,path:"/studio"},{id:"files",name:"Files",icon:FolderOpen,path:"/studio"},{id:"canvas",name:"Canvas",icon:LayoutGrid,path:"#canvas"},{id:"memory",name:"Memory",icon:Brain,path:"#memory"},{id:"agents",name:"Agents",icon:Users,path:"/studio"},{id:"tasks",name:"Tasks",icon:Workflow,path:"/studio"}
];
const personas=["Pulse","Forge","Ghost","Nova","Sentinel","Echo","Titan"];
const actions=["Rewrite","Summarize","Translate","Explain","Code","Image","Improve"];

export default function XyronOS(){
 const nav=useNavigate(); const [q,setQ]=useState(""); const [palette,setPalette]=useState(false); const [orbit,setOrbit]=useState(true); const [persona,setPersona]=useState(()=>localStorage.getItem("xyron_persona")||"Pulse"); const [dna,setDna]=useState(()=>JSON.parse(localStorage.getItem("xyron_prompt_dna")||"[]")); const [xp,setXp]=useState(()=>Number(localStorage.getItem("xyron_xp")||0)); const [memory,setMemory]=useState(()=>JSON.parse(localStorage.getItem("xyron_memory_timeline")||"[]")); const [note,setNote]=useState(""); const [selected,setSelected]=useState("Rewrite"); const [copied,setCopied]=useState(false);
 useEffect(()=>localStorage.setItem("xyron_persona",persona),[persona]); useEffect(()=>localStorage.setItem("xyron_prompt_dna",JSON.stringify(dna)),[dna]); useEffect(()=>{localStorage.setItem("xyron_xp",xp);},[xp]); useEffect(()=>localStorage.setItem("xyron_memory_timeline",JSON.stringify(memory)),[memory]);
 useEffect(()=>{const fn=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)} if(e.key==="Escape")setPalette(false)};window.addEventListener("keydown",fn);return()=>window.removeEventListener("keydown",fn)},[]);
 const filtered=useMemo(()=>modules.filter(m=>m.name.toLowerCase().includes(q.toLowerCase())),[q]);
 const addMemory=()=>{if(!note.trim())return;setMemory([{id:Date.now(),text:note.trim(),at:new Date().toLocaleString()},...memory]);setNote("");setXp(xp+10)};
 const applyAction=()=>{setDna([...new Set([...dna,selected])]);setXp(xp+5)};
 const share=async()=>{const data=btoa(unescape(encodeURIComponent(JSON.stringify({persona,dna,memory,xp}))));const link=location.origin+"/os#"+data;await navigator.clipboard?.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1400)};
 const level=Math.floor(xp/100)+1;
 return <div className="min-h-screen bg-[#050505] text-white md:pl-72">
  <header className="sticky top-0 z-30 border-b border-white/10 bg-black/70 backdrop-blur-2xl"><div className="flex items-center justify-between px-5 py-4"><div><div className="text-[10px] uppercase tracking-[.35em] text-neutral-600">XYRON OS</div><h1 className="text-xl font-semibold">Your AI operating system</h1></div><div className="flex gap-2"><button className="rounded-xl border border-white/10 px-3 py-2 text-xs text-neutral-400 hover:text-white" onClick={()=>setPalette(true)}><Command className="mr-2 inline h-4 w-4"/>Ctrl K</button><button className="rounded-xl border border-white/10 px-3 py-2 text-xs" onClick={()=>setOrbit(!orbit)}>{orbit?"Hide Orbit":"Show Orbit"}</button></div></div></header>
  <main className="mx-auto max-w-7xl p-5">
   <section className="grid gap-4 lg:grid-cols-[1.5fr_.8fr]">
    <div className={`${glass} p-6`}><div className="flex items-center gap-3"><div className="rounded-2xl border border-white/15 bg-white/10 p-3"><Orbit className="h-6 w-6"/></div><div><div className="text-xs uppercase tracking-[.25em] text-neutral-600">Orbit Core</div><h2 className="text-2xl font-semibold">Everything connected.</h2></div></div><p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-500">Chat, code, research, files, images, memory, agents and tasks share one workspace. Use the command palette or Orbit to jump anywhere.</p><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{filtered.map(m=>{const I=m.icon;return <button key={m.id} onClick={()=>m.path.startsWith("/")?nav(m.path):document.getElementById(m.id)?.scrollIntoView({behavior:"smooth"})} className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-left transition hover:border-white/20 hover:bg-white/[.07]"><I className="mb-2 h-4 w-4 text-neutral-400"/><div className="text-sm">{m.name}</div></button>})}</div><div className="mt-4 relative"><Search className="absolute left-3 top-3 h-4 w-4 text-neutral-700"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/40 py-2.5 pl-10 pr-3 text-sm outline-none placeholder:text-neutral-700" placeholder="Search your Xyron OS…"/></div></div>
    <div className={`${glass} p-6`}><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-[.25em] text-neutral-600">Xyron XP</span><Zap className="h-4 w-4"/></div><div className="mt-4 text-4xl font-bold">LVL {level}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-white" style={{width:`${xp%100}%`}}/></div><p className="mt-2 text-xs text-neutral-600">{xp%100}/100 XP to next level</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl border border-white/10 p-3">Persona<br/><b>{persona}</b></div><div className="rounded-xl border border-white/10 p-3">Memories<br/><b>{memory.length}</b></div></div></div>
   </section>

   <section className="mt-4 grid gap-4 lg:grid-cols-2">
    <div className={`${glass} p-5`}><div className="mb-4 flex items-center gap-2"><Sparkles className="h-4 w-4"/><h2 className="font-semibold">Xyron Personas</h2></div><div className="flex flex-wrap gap-2">{personas.map(p=><button key={p} onClick={()=>{setPersona(p);setXp(xp+3)}} className={`rounded-full border px-3 py-2 text-xs ${persona===p?"border-white/30 bg-white/10":"border-white/10 text-neutral-500"}`}>{p}</button>)}</div><p className="mt-4 text-xs text-neutral-600">{persona} is active across this workspace. Persona selection is stored locally.</p></div>
    <div className={`${glass} p-5`}><div className="mb-4 flex items-center gap-2"><Wand2 className="h-4 w-4"/><h2 className="font-semibold">Magic Actions</h2></div><div className="flex flex-wrap gap-2">{actions.map(a=><button key={a} onClick={()=>{setSelected(a);applyAction()}} className={`rounded-xl border px-3 py-2 text-xs ${selected===a?"border-white/25 bg-white/10":"border-white/10 text-neutral-500"}`}>{a}</button>)}</div><p className="mt-4 text-xs text-neutral-600">Selected action: <b className="text-neutral-300">{selected}</b>. Use this as the default action when working with highlighted content.</p></div>
   </section>

   <section id="canvas" className="mt-4 grid gap-4 lg:grid-cols-[1.2fr_.8fr]">
    <div className={`${glass} min-h-[330px] p-5`}><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Infinite Canvas</h2><p className="text-xs text-neutral-600">A lightweight workspace for connected ideas.</p></div><button className="rounded-xl border border-white/10 p-2" onClick={()=>setXp(xp+5)}><Plus className="h-4 w-4"/></button></div><div className="grid min-h-[250px] place-items-center rounded-2xl border border-dashed border-white/10 bg-black/30 text-center"><div><LayoutGrid className="mx-auto mb-3 h-8 w-8 text-neutral-700"/><p className="text-sm text-neutral-500">Drop ideas, prompts, images and code here.</p><p className="mt-1 text-xs text-neutral-700">Canvas persistence can be connected to your backend later.</p></div></div></div>
    <div id="memory" className={`${glass} p-5`}><div className="mb-4 flex items-center gap-2"><Brain className="h-4 w-4"/><h2 className="font-semibold">Ghost Memory Timeline</h2></div><div className="flex gap-2"><input value={note} onChange={e=>setNote(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addMemory()} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/40 px-3 py-2 text-sm outline-none" placeholder="Save a workspace memory…"/><button onClick={addMemory} className="rounded-xl border border-white/10 px-3"><Send className="h-4 w-4"/></button></div><div className="mt-4 max-h-56 space-y-2 overflow-auto">{memory.length?memory.map(x=><div key={x.id} className="rounded-xl border border-white/10 p-3"><p className="text-sm">{x.text}</p><p className="mt-1 text-[10px] text-neutral-700">{x.at}</p></div>):<p className="text-xs text-neutral-700">Your workspace timeline will appear here.</p>}</div></div>
   </section>

   <section className={`${glass} mt-4 p-5`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Prompt DNA</h2><p className="text-xs text-neutral-600">Xyron remembers the action styles you choose in this browser.</p></div><button onClick={share} className="rounded-xl border border-white/10 px-3 py-2 text-xs">{copied?<><Check className="mr-1 inline h-3 w-3"/>Copied</>:<><Copy className="mr-1 inline h-3 w-3"/>Share OS state</>}</button></div><div className="mt-4 flex flex-wrap gap-2">{dna.length?dna.map(x=><span key={x} className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs">{x}</span>):<span className="text-xs text-neutral-700">No DNA preferences yet.</span>}</div></section>
  </main>
  {orbit&&<button onClick={()=>setPalette(true)} className="fixed bottom-6 right-6 z-40 grid h-16 w-16 place-items-center rounded-full border border-white/20 bg-white/10 shadow-2xl backdrop-blur-2xl transition hover:scale-105"><Orbit className="h-7 w-7"/><span className="absolute -top-1 -right-1 h-3 w-3 rounded-full bg-white"/></button>}
  {palette&&<div className="fixed inset-0 z-50 bg-black/75 p-5 backdrop-blur-md" onClick={()=>setPalette(false)}><div onClick={e=>e.stopPropagation()} className="mx-auto mt-[12vh] max-w-xl rounded-3xl border border-white/15 bg-[#0a0a0a]/95 p-4 shadow-2xl"><div className="flex items-center gap-2 border-b border-white/10 pb-3"><Command className="h-4 w-4 text-neutral-500"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} className="flex-1 bg-transparent text-sm outline-none" placeholder="Type a command…"/></div><div className="mt-3 grid gap-1">{[...modules,{id:"share",name:"Share Workspace",icon:Copy,path:"#share"},{id:"security",name:"Security",icon:Shield,path:"/settings"},{id:"voice",name:"Voice Mode",icon:Mic,path:"/studio"}].filter(x=>x.name.toLowerCase().includes(q.toLowerCase())).map(x=>{const I=x.icon;return <button key={x.id} onClick={()=>{setPalette(false);x.path.startsWith("/")?nav(x.path):null}} className="flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm hover:bg-white/10"><I className="h-4 w-4 text-neutral-500"/>{x.name}</button>})}</div></div></div>}
 </div>
}

