import React from "react";
import LegalLayout, { LegalSection } from "../components/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" updated="September 27, 2026">
      <LegalSection title="Agreement">
        <p>By using Xyron, you agree to these terms. If you don't agree, please don't use the service.</p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>You're responsible for keeping your login secure and for activity on your account. You must be old enough to legally agree to these terms in your country.</p>
      </LegalSection>

      <LegalSection title="Plans & billing">
        <p>Xyron offers Free, Premium, and Premium+ plans with different usage limits. Paid plans renew until cancelled; you can cancel anytime from the Premium page and keep access until the end of the billing period.</p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>Don't use Xyron for anything illegal, harmful, or abusive — including attempts to break, overload, or reverse-engineer the service, or to generate content that violates others' rights.</p>
      </LegalSection>

      <LegalSection title="AI-generated content">
        <p>Responses are generated by AI and can be inaccurate or incomplete. Use your judgment, especially for anything important — medical, legal, or financial decisions included.</p>
      </LegalSection>

      <LegalSection title="Your content">
        <p>You keep ownership of what you upload or write. By using Xyron, you give us permission to process it in order to provide the service.</p>
      </LegalSection>

      <LegalSection title="Termination">
        <p>You can stop using Xyron and delete your account anytime. We may suspend or terminate accounts that violate these terms.</p>
      </LegalSection>

      <LegalSection title="Disclaimer">
        <p>Xyron is provided "as is," without warranties of any kind. We aren't liable for indirect or consequential damages arising from your use of the service, to the extent permitted by law.</p>
      </LegalSection>

      <LegalSection title="Changes">
        <p>We may update these terms from time to time; the date at the top will change when we do. Continuing to use Xyron means you accept the current terms.</p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>Questions about these terms? Reach us from the Help section in Settings.</p>
      </LegalSection>
    </LegalLayout>
  );
}
