import React,{useMemo,useState,useEffect} from "react";
import {api} from "../api/client";
import {useNavigate} from "react-router-dom";
import {Bot,Brain,Code2,Globe2,FolderOpen,Workflow,Shield,Search,Plus,Play,Trash2,KeyRound,Users,Store,Mic,Eye,Video,Wand2,ChevronRight} from "lucide-react";
const glass="rounded-2xl border border-white/10 bg-white/[.035] backdrop-blur-xl";
const toolset=["Web Research","Project Intelligence","Codebase AI","Vision","Voice","Image Studio","Workflow Builder","Cloud Code Runner"];
const starter=[
 {name:"Debug a project",desc:"Inspect project structure and trace an issue.",icon:Code2},
 {name:"Research a topic",desc:"Plan research, gather sources and summarize findings.",icon:Globe2},
 {name:"Build a workflow",desc:"Create Trigger → AI → Tool → Action automations.",icon:Workflow},
 {name:"Analyze an image",desc:"Use vision instructions against an uploaded image.",icon:Eye}
];
export default function XyronIntelligence(){
 const nav=useNavigate(); const [goal,setGoal]=useState(""); const [logs,setLogs]=useState(()=>JSON.parse(localStorage.getItem("xyron_intelligence_logs")||"[]")); const [tools,setTools]=useState(()=>JSON.parse(localStorage.getItem("xyron_tools")||"[]")); const [workflow,setWorkflow]=useState(()=>JSON.parse(localStorage.getItem("xyron_workflows")||"[]"));
 const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/intelligence/activity",{credentials:"include"});if(r.ok){const j=await r.json();const remote=(j.activity||[]).map(x=>({id:x.id,goal:x.goal,status:x.status||"Planned",at:x.created_date,plan:x.plan}));if(remote.length){setLogs(remote);save("xyron_intelligence_logs",remote)}}}catch{}})()},[]);
 const run=async()=>{if(!goal.trim())return;const item={id:Date.now(),goal:goal.trim(),status:"Planned",at:new Date().toLocaleString()};try{const r=await api.functions.invoke("intelligencePlan",{goal:goal.trim()});item.server_id=r.data?.plan?.id||null;item.plan=r.data?.plan?.plan||null;item.status="Backend planned"}catch{}const next=[item,...logs];setLogs(next);save("xyron_intelligence_logs",next);setGoal("")};
 const addTool=()=>{const name=prompt("Tool name");if(!name?.trim())return;const next=[{id:Date.now(),name:name.trim(),created:new Date().toLocaleString()},...tools];setTools(next);save("xyron_tools",next)};
 const addWorkflow=()=>{const name=prompt("Workflow name");if(!name?.trim())return;const next=[{id:Date.now(),name:name.trim(),steps:["Trigger","AI","Tool","Action"]},...workflow];setWorkflow(next);save("xyron_workflows",next)};
 const stats=useMemo(()=>({runs:logs.length,tools:tools.length,flows:workflow.length}),[logs,tools,workflow]);
 return <div className="min-h-screen bg-[#050505] text-white md:pl-72"><header className="sticky top-0 z-30 border-b border-white/10 bg-black/70 backdrop-blur-2xl"><div className="flex items-center justify-between px-5 py-4"><div><div className="text-[10px] uppercase tracking-[.35em] text-neutral-600">XYRON INTELLIGENCE</div><h1 className="text-xl font-semibold">One brain. Every Xyron tool.</h1></div><button onClick={()=>nav("/os")} className="rounded-xl border border-white/10 px-3 py-2 text-xs">Open Xyron OS <ChevronRight className="ml-1 inline h-3 w-3"/></button></div></header>
 <main className="mx-auto max-w-7xl p-5"><section className="grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><div className={`${glass} p-6`}><div className="flex items-center gap-3"><div className="rounded-2xl border border-white/15 bg-white/10 p-3"><Brain className="h-6 w-6"/></div><div><div className="text-xs uppercase tracking-[.25em] text-neutral-600">Xyron Brain</div><h2 className="text-2xl font-semibold">Tell Xyron what you want done.</h2></div></div><p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-500">The intelligence layer plans work across chat, code, research, files, vision, agents and automations while keeping your existing app structure intact.</p><div className="mt-5 flex gap-2"><input value={goal} onChange={e=>setGoal(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm outline-none" placeholder="e.g. Find why signup emails are failing…"/><button onClick={run} className="rounded-xl border border-white/15 bg-white/10 px-4 text-sm"><Play className="mr-2 inline h-4 w-4"/>Plan</button></div></div><div className={`${glass} p-6`}><div className="text-xs uppercase tracking-[.25em] text-neutral-600">Workspace stats</div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl border border-white/10 p-3"><b className="text-xl">{stats.runs}</b><p className="text-[10px] text-neutral-600">runs</p></div><div className="rounded-xl border border-white/10 p-3"><b className="text-xl">{stats.tools}</b><p className="text-[10px] text-neutral-600">tools</p></div><div className="rounded-xl border border-white/10 p-3"><b className="text-xl">{stats.flows}</b><p className="text-[10px] text-neutral-600">flows</p></div></div></div></section>
 <section className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{starter.map(({name,desc,icon:I})=><button key={name} onClick={()=>setGoal(name+": ")} className={`${glass} p-5 text-left hover:bg-white/[.06]`}><I className="h-5 w-5 text-neutral-400"/><h3 className="mt-4 text-sm font-semibold">{name}</h3><p className="mt-1 text-xs leading-5 text-neutral-600">{desc}</p></button>)}</section>
 <section className="mt-4 grid gap-4 lg:grid-cols-2"><div className={`${glass} p-5`}><div className="flex items-center justify-between"><div><h2 className="font-semibold">Tool Builder</h2><p className="text-xs text-neutral-600">Create reusable tool definitions.</p></div><button onClick={addTool} className="rounded-xl border border-white/10 p-2"><Plus className="h-4 w-4"/></button></div><div className="mt-4 space-y-2">{tools.length?tools.map(t=><div key={t.id} className="flex items-center justify-between rounded-xl border border-white/10 p-3"><span className="text-sm">{t.name}</span><span className="text-[10px] text-neutral-700">local tool</span></div>):<p className="text-xs text-neutral-700">No custom tools yet.</p>}</div></div><div className={`${glass} p-5`}><div className="flex items-center justify-between"><div><h2 className="font-semibold">Workflow Builder</h2><p className="text-xs text-neutral-600">Trigger → AI → Tool → Action.</p></div><button onClick={addWorkflow} className="rounded-xl border border-white/10 p-2"><Plus className="h-4 w-4"/></button></div><div className="mt-4 space-y-2">{workflow.length?workflow.map(w=><div key={w.id} className="rounded-xl border border-white/10 p-3"><div className="text-sm">{w.name}</div><div className="mt-2 flex flex-wrap gap-1">{w.steps.map(s=><span key={s} className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-neutral-500">{s}</span>)}</div></div>):<p className="text-xs text-neutral-700">No workflows yet.</p>}</div></div></section>
 <section className={`${glass} mt-4 p-5`}><div className="flex items-center gap-2"><Wand2 className="h-4 w-4"/><h2 className="font-semibold">Xyron capabilities</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{toolset.map(x=><div key={x} className="rounded-xl border border-white/10 bg-black/20 p-3 text-xs text-neutral-400">{x}</div>)}</div></section>
 <section className={`${glass} mt-4 p-5`}><div className="flex items-center justify-between"><div><h2 className="font-semibold">Intelligence Activity</h2><p className="text-xs text-neutral-600">Plans and actions saved locally for this workspace.</p></div>{logs.length>0&&<button onClick={()=>{setLogs([]);save("xyron_intelligence_logs",[])}} className="rounded-xl border border-white/10 px-3 py-2 text-xs"><Trash2 className="mr-1 inline h-3 w-3"/>Clear</button>}</div><div className="mt-4 space-y-2">{logs.length?logs.map(x=><div key={x.id} className="rounded-xl border border-white/10 p-3"><div className="text-sm">{x.goal}</div><div className="mt-1 text-[10px] text-neutral-600">{x.status} · {x.at}</div></div>):<p className="text-xs text-neutral-700">No activity yet.</p>}</div></section>
 <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[["Vault","/settings",KeyRound],["Teams","/studio",Users],["Marketplace","/studio",Store],["Voice","/studio",Mic],["Automations","/studio",Workflow]].map(([n,p,I])=><button key={n} onClick={()=>nav(p)} className="rounded-xl border border-white/10 p-3 text-left text-xs text-neutral-500 hover:text-white"><I className="mr-2 inline h-4 w-4"/>{n}</button>)}</div>
 </main></div>
}


