import React, {useEffect, useRef, useState} from "react";
import {api} from "../api/client";
import {XYRON_PERSONA_PROMPT, XYRON_RESPONSE_STYLE_PROMPT} from "../lib/persona";
import {useNavigate} from "react-router-dom";
import {Bot, Globe2, FileSearch, Mic, Image as ImageIcon, Video, Users, Clock3, Share2, Code2, Play, Plus, Trash2, Copy, Check, Sparkles} from "lucide-react";

const TABS=[
  ["agent","Agent Mode",Bot],["research","Web Research",Globe2],["files","File Lab",FileSearch],["voice","Voice",Mic],["image","Image Studio",ImageIcon],["video","Video Studio",Video],["agents","Custom Agents",Users],["automation","Automations",Clock3],["share","Share",Share2],["runner","Code Runner",Code2]
];
const glass="rounded-2xl border border-white/10 bg-white/[.035] backdrop-blur-xl";

export default function XyronStudio(){
 const navigate=useNavigate();
 const [tab,setTab]=useState("agent"); const [busy,setBusy]=useState(false); const [result,setResult]=useState(""); const [copied,setCopied]=useState(false);
 const [agentGoal,setAgentGoal]=useState(""); const [research,setResearch]=useState(""); const [file,setFile]=useState(null); const [voiceText,setVoiceText]=useState(""); const [video,setVideo]=useState(null); const [code,setCode]=useState("console.log('Hello from Xyron');"); const [output,setOutput]=useState("");
 const [agents,setAgents]=useState(()=>JSON.parse(localStorage.getItem("xyron_custom_agents")||"[]"));
 const [agentName,setAgentName]=useState(""); const [agentPrompt,setAgentPrompt]=useState(""); const [automations,setAutomations]=useState(()=>JSON.parse(localStorage.getItem("xyron_automations")||"[]")); const [autoName,setAutoName]=useState(""); const [autoSchedule,setAutoSchedule]=useState("Every day at 09:00");
 const recognition=useRef(null);
 useEffect(()=>{localStorage.setItem("xyron_custom_agents",JSON.stringify(agents))},[agents]); useEffect(()=>{localStorage.setItem("xyron_automations",JSON.stringify(automations))},[automations]);
 const runChat=async(prompt,files=[])=>{setBusy(true);setResult("");try{const urls=[];for(const f of files){const r=await api.integrations.Core.UploadFile({file:f});urls.push(r.file_url)}const r=await api.functions.invoke("xryonChat",{messages:[{role:"user",content:prompt}],file_urls:urls,system_prompt:[XYRON_PERSONA_PROMPT,XYRON_RESPONSE_STYLE_PROMPT].join("\n\n")});setResult(r.data?.reply||r.data?.error||"No response returned.")}catch(e){setResult(e.message||"This feature needs the Xyron backend endpoint enabled.")}finally{setBusy(false)}};
 const startVoice=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setVoiceText("Voice input is not supported by this browser.");return} recognition.current=new SR();recognition.current.continuous=false;recognition.current.interimResults=true;recognition.current.onresult=e=>setVoiceText(Array.from(e.results).map(x=>x[0].transcript).join(""));recognition.current.start()};
 const runCode=()=>{try{const logs=[];const fn=new Function("console",code);fn({log:(...x)=>logs.push(x.map(v=>typeof v==='object'?JSON.stringify(v):String(v)).join(" "))});setOutput(logs.join("\n")||"✓ Code finished with no console output.")}catch(e){setOutput("✕ "+e.message)}};
 const share=()=>{const data=btoa(unescape(encodeURIComponent(JSON.stringify({title:"Xyron shared workspace",content:result||"Shared from Xyron",createdAt:Date.now()}))));const link=location.origin+"/share#"+data;navigator.clipboard?.writeText(link);setResult(link);setCopied(true);setTimeout(()=>setCopied(false),1600)};
 const addAgent=()=>{if(!agentName.trim())return;setAgents([...agents,{id:Date.now(),name:agentName,prompt:agentPrompt||"Helpful Xyron agent",createdAt:Date.now()}]);setAgentName("");setAgentPrompt("")};
 const addAuto=()=>{if(!autoName.trim())return;setAutomations([...automations,{id:Date.now(),name:autoName,schedule:autoSchedule,active:true}]);setAutoName("")};
 return <div className="min-h-screen bg-[#050505] text-neutral-100 md:pl-72"><div className="border-b border-white/10 bg-black/30 px-5 py-4 backdrop-blur-xl"><div className="mx-auto max-w-6xl"><p className="text-[10px] uppercase tracking-[.28em] text-neutral-600">Xyron Studio</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">One workspace. Every AI tool.</h1><p className="mt-1 text-sm text-neutral-500">Agent, research, files, voice, images, video, automations and code.</p><button onClick={()=>navigate("/os")} className="mt-3 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs text-neutral-300 hover:bg-white/10">Open Xyron OS →</button></div></div>
 <div className="mx-auto max-w-6xl p-5"><div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-5">{TABS.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`${glass} flex items-center gap-2 p-3 text-left text-xs ${tab===id?"border-white/25 bg-white/10 text-white":"text-neutral-500 hover:text-white"}`}><Icon className="h-4 w-4"/><span>{label}</span></button>)}</div>
 <section className={`${glass} min-h-[520px] p-5`}>
 {tab==="agent"&&<Panel title="Agent Mode" icon={Bot} desc="Give Xyron a goal. It plans the work and can hand the final task to your existing chat backend."><textarea value={agentGoal} onChange={e=>setAgentGoal(e.target.value)} placeholder="Build me a landing page for a futuristic AI app..." className="input h-32"/><button disabled={busy||!agentGoal.trim()} onClick={()=>runChat(`Act as an autonomous Xyron agent. Break this goal into clear steps, reason about dependencies, and produce the best practical result. Goal: ${agentGoal}`)} className="btn mt-3"><Play className="h-4 w-4"/> Run agent</button><Output busy={busy} result={result}/></Panel>}
 {tab==="research"&&<Panel title="Web Research" icon={Globe2} desc="Research-ready interface. Connect your server-side web-search tool to enable live sources."><input value={research} onChange={e=>setResearch(e.target.value)} placeholder="What should Xyron research?" className="input"/><button disabled={busy||!research.trim()} onClick={()=>runChat(`Research this topic thoroughly. Identify key facts, competing viewpoints, dates, and provide a source-ready structured report: ${research}`)} className="btn mt-3"><Globe2 className="h-4 w-4"/> Research</button><Output busy={busy} result={result}/></Panel>}
 {tab==="files"&&<Panel title="File Lab" icon={FileSearch} desc="Upload a document and ask Xyron to analyze it. Your existing upload API is reused."><label className="drop"><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><FileSearch className="h-6 w-6"/><span>{file?.name||"Choose PDF, DOCX, CSV, TXT or another file"}</span></label><button disabled={busy||!file} onClick={()=>runChat("Analyze the uploaded file. Summarize it, extract important facts, identify risks or errors, and give useful next actions.",[file])} className="btn mt-3"><Sparkles className="h-4 w-4"/> Analyze file</button><Output busy={busy} result={result}/></Panel>}
 {tab==="voice"&&<Panel title="Voice Mode" icon={Mic} desc="Browser-native speech input, ready to feed into Xyron chat or your voice backend."><div className="rounded-2xl border border-white/10 bg-black/30 p-5 text-sm text-neutral-300 min-h-36">{voiceText||"Press the microphone and start speaking..."}</div><button onClick={startVoice} className="btn mt-3"><Mic className="h-4 w-4"/> Start listening</button></Panel>}
 {tab==="image"&&<Panel title="AI Image Studio" icon={ImageIcon} desc="Your existing /anime, /manga, /cinematic and image-to-image system can be launched from here."><div className="grid gap-3 sm:grid-cols-3">{["/anime","/manga","/cinematic","/portrait","/cyberpunk","/product","/remove","/changebg","/enhance"].map(x=><button key={x} onClick={()=>location.href="/?prompt="+encodeURIComponent(x)} className="rounded-xl border border-white/10 bg-white/[.03] p-4 text-left text-sm hover:bg-white/10">{x}</button>)}</div><p className="mt-5 text-xs text-neutral-600">Image generation still uses your existing generateImage endpoint; image editing requires that backend to accept source images.</p></Panel>}
 {tab==="video"&&<Panel title="AI Video Studio" icon={Video} desc="Video workspace for upload, analysis and future generation providers."><label className="drop"><input type="file" accept="video/*" onChange={e=>setVideo(e.target.files?.[0]||null)}/><Video className="h-6 w-6"/><span>{video?.name||"Choose a video"}</span></label>{video&&<video controls className="mt-4 max-h-72 w-full rounded-xl border border-white/10" src={URL.createObjectURL(video)}/>}<button disabled={!video||busy} onClick={()=>runChat("Analyze this uploaded video. Describe scenes, important moments, visible text, pacing, and editing suggestions.",[video])} className="btn mt-3"><Sparkles className="h-4 w-4"/> Analyze video</button><Output busy={busy} result={result}/></Panel>}
 {tab==="agents"&&<Panel title="Custom Agents" icon={Users} desc="Create reusable Xyron personas with their own instructions."><div className="grid gap-3 sm:grid-cols-2"><input value={agentName} onChange={e=>setAgentName(e.target.value)} placeholder="Agent name" className="input"/><input value={agentPrompt} onChange={e=>setAgentPrompt(e.target.value)} placeholder="Instructions / personality" className="input"/></div><button onClick={addAgent} className="btn mt-3"><Plus className="h-4 w-4"/> Create agent</button><div className="mt-5 space-y-2">{agents.map(a=><div className="flex items-center justify-between rounded-xl border border-white/10 p-4" key={a.id}><div><b>{a.name}</b><p className="text-xs text-neutral-600">{a.prompt}</p></div><button onClick={()=>setAgents(agents.filter(x=>x.id!==a.id))}><Trash2 className="h-4 w-4 text-neutral-600"/></button></div>)}</div></Panel>}
 {tab==="automation"&&<Panel title="Automations" icon={Clock3} desc="Build scheduled workflows. The UI persists locally; connect your scheduler/worker for execution."><div className="grid gap-3 sm:grid-cols-2"><input value={autoName} onChange={e=>setAutoName(e.target.value)} placeholder="Automation name" className="input"/><input value={autoSchedule} onChange={e=>setAutoSchedule(e.target.value)} className="input"/></div><button onClick={addAuto} className="btn mt-3"><Plus className="h-4 w-4"/> Add automation</button><div className="mt-5 space-y-2">{automations.map(a=><div key={a.id} className="flex items-center justify-between rounded-xl border border-white/10 p-4"><div><b>{a.name}</b><p className="text-xs text-neutral-600">{a.schedule} • {a.active?"Active":"Paused"}</p></div><button onClick={()=>setAutomations(automations.filter(x=>x.id!==a.id))}><Trash2 className="h-4 w-4 text-neutral-600"/></button></div>)}</div></Panel>}
 {tab==="share"&&<Panel title="Share Workspace" icon={Share2} desc="Create a portable share link for the current result. For secure public sharing, add server-side share storage later."><div className="rounded-2xl border border-white/10 bg-black/30 p-5 text-sm text-neutral-400">{result||"Generate a share link from your current Studio result."}</div><button onClick={share} className="btn mt-3">{copied?<Check className="h-4 w-4"/>:<Copy className="h-4 w-4"/>}{copied?"Copied":"Create share link"}</button></Panel>}
 {tab==="runner"&&<Panel title="Code Runner" icon={Code2} desc="Quick browser sandbox for JavaScript experiments. For production code execution, connect a real isolated server sandbox."><textarea value={code} onChange={e=>setCode(e.target.value)} className="input h-64 font-mono text-xs"/><button onClick={runCode} className="btn mt-3"><Play className="h-4 w-4"/> Run JavaScript</button><pre className="mt-4 min-h-24 overflow-auto rounded-xl border border-white/10 bg-black/50 p-4 text-xs text-neutral-300">{output||"Console output will appear here."}</pre></Panel>}
 </section></div></div>
}
function Panel({title,icon:Icon,desc,children}){return <><div className="mb-6 flex items-start gap-3"><div className="rounded-xl border border-white/10 bg-white/5 p-3"><Icon className="h-5 w-5"/></div><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-neutral-600">{desc}</p></div></div>{children}</>}
function Output({busy,result}){return <div className="mt-5">{busy&&<div className="text-xs text-neutral-600">Xyron is working…</div>}{result&&<pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded-2xl border border-white/10 bg-black/40 p-5 text-sm leading-6 text-neutral-300">{result}</pre>}</div>}


